/*
 * Keywords.cpp
 *
 *  Created on: Oct 31, 2011
 *      Author: alienjon
 */
#include "Keywords.hpp"

using std::string;

const string ACTION_PAUSE = "ACTION_PAUSE";
const string ACTION_TO_MAINMENU = "ACTION_TO_MAINMENU";
const string ACTION_SLIDE_CREDITSMENU = "ACTION_SLIDE_CREDITSMENU";
const string ACTION_SLIDE_MAINMENU = "ACTION_SLIDE_MAINMENU";
const string ACTION_SLIDE_NEWMENU = "ACTION_SLIDE_NEWMENU";
const string ACTION_SLIDE_OPTIONSMENU = "ACTION_SLIDE_OPTIONSMENU";
const string ACTION_SLIDE_STARTGAME = "ACTION_SLIDE_STARTGAME";
const string ACTION_STARTGAME_EASY = "ACTION_STARTGAME_EASY";
const string ACTION_STARTGAME_HARD = "ACTION_STARTGAME_HARD";
const string ACTION_STARTGAME_NORMAL = "ACTION_STARTGAME_NORMAL";
const string ACTION_UNPAUSE = "ACTION_UNPAUSE";
const string ACTION_QUIT = "ACTION_QUIT";
